spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    defaultSchemaName: public
mybatis:
  mapper-locations: 'classpath:/mybatis/*.xml'